# Generated by Django 2.2.11 on 2020-03-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserKur',
            fields=[
                ('logi_id', models.AutoField(primary_key=True, serialize=False)),
                ('namekurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cite.Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cite.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namekat', models.CharField(max_length=100)),
                ('publishedkat_date', models.DateTimeField(blank=True, null=True)),
                ('nametheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cite.Kurs')),
            ],
        ),
    ]
