# Generated by Django 2.2.11 on 2020-03-10 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cite', '0002_auto_20200310_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='nametheme',
        ),
        migrations.AddField(
            model_name='theme',
            name='nametheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='cite.Kurs'),
            preserve_default=False,
        ),
    ]
